# Generated by Django 2.2 on 2019-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
