# Generated by Django 2.2 on 2019-10-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191012_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='compleat_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fixed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
