# Generated by Django 2.2 on 2020-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191014_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyainTable',
            fields=[
                ('SyainNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
