# Generated by Django 2.2 on 2020-05-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_syaintable'),
    ]

    operations = [
        migrations.CreateModel(
            name='KojinTourokuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
