# Generated by Django 2.2 on 2020-05-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_kojintourokutable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kojintourokutable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
