# Generated by Django 2.2 on 2020-06-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200602_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kojintourokutable',
            name='KojinTourokuNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kojintourokutable',
            name='SyainNo',
            field=models.IntegerField(default=1),
        ),
    ]
